name: 'SIMULATIONPAGESTATIC'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
       java-version: 1.11
       
       
    - name: zentest
      run: |
          gh run download -n Package -R DevGrammo/simulation-static-page-generator --dir ./build
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash  
       

    - name: test-zen
      run: echo | ls build
      shell: bash
       
    - name: Run chmod to make gradlew executable 
      run: chmod +x ./gradlew && ./gradlew shadowJar && java -jar build/libs/PageGenerator-1.0-SNAPSHOT-all.jar .
      shell: bash
    

